"""
Listy - AI Powered To-Do List Application
=========================================

Main entry point for the Flet application.
This module handles:
- App initialization and configuration
- Window settings
- Theme management
- Navigation and View orchestration
- Integration of TodoView, Settings, and AI Chat

Author: Steven Mende (generated by DeepMind AI)
"""
import flet as ft
from views.todo_view import TodoView
from styles import Colors
from storage.data_manager import DataManager
from utils.translations import LanguageManager

import datetime
import threading
import time
import urllib.parse

import logging
import sys

sys.stderr.flush()

def main(page: ft.Page):
    try:
        # --- Managers ---
        data_manager = DataManager(page)
        settings = data_manager.get_settings()
        
        # Initialize Language
        lang_code = settings.get("language", "en")
        lang_manager = LanguageManager(lang_code)
        
        # --- Page Config ---
        page.title = lang_manager.get_text("app_title")
        page.window.width = 380
        page.window.height = 640
        # Try to enforce icon on window level
        # Note: On macOS Dock icons are handled by the bundle, but this might help window decorations if any
        # or the task switcher.

        
        # Theme Setup
        theme_mode_str = settings.get("theme_mode", "dark") # Default to Dark
        page.theme_mode = ft.ThemeMode.DARK if theme_mode_str == "dark" else ft.ThemeMode.LIGHT
        
        page.theme = ft.Theme(
            color_scheme=ft.ColorScheme(
                primary=Colors.LAVENDER,
                secondary=Colors.LAVENDER_LIGHT,
            )
        )

        # --- helper for translation ---
        def _t(key):
            return lang_manager.get_text(key)

        # --- Setup App State ---
        
        # We will hold references to UI elements that need text updates
        title_text = ft.Text(_t("my_tasks"), size=24, weight=ft.FontWeight.BOLD)
        
        # Create the View
        todo_view = TodoView(data_manager, lang_manager) # Pass instances

        # --- Actions ---
        
        def toggle_theme_mode(e):
            if page.theme_mode == ft.ThemeMode.LIGHT:
                page.theme_mode = ft.ThemeMode.DARK
                theme_icon.icon = ft.Icons.LIGHT_MODE
                theme_icon.tooltip = _t("light_mode")
                data_manager.update_setting("theme_mode", "dark")
            else:
                page.theme_mode = ft.ThemeMode.LIGHT
                theme_icon.icon = ft.Icons.DARK_MODE
                theme_icon.tooltip = _t("dark_mode")
                data_manager.update_setting("theme_mode", "light")
            
            # Explicitly update Title Text Color
            is_light = page.theme_mode == ft.ThemeMode.LIGHT
            title_text.color = ft.Colors.BLACK if is_light else ft.Colors.WHITE
            title_text.update()

            todo_view.refresh_view()
            page.update()

        def toggle_mode(e):
            current_mode = data_manager.get_settings().get("mode", "todo")
            new_mode = "shopping" if current_mode == "todo" else "todo"
            
            data_manager.update_setting("mode", new_mode)
            
            # Update UI Icon/Tooltip
            update_mode_icon(new_mode)
            
            # Update Footer
            update_footer(new_mode)
            
            # Refresh View
            todo_view.refresh_view()
            page.update()

        def update_mode_icon(mode):
            if mode == "todo":
                mode_icon.icon = ft.Icons.SHOPPING_CART
                mode_icon.tooltip = _t("mode_shopping") # Tooltip shows what clicking DOES
            else:
                mode_icon.icon = ft.Icons.LIST_ALT
                mode_icon.tooltip = _t("mode_todo")

        def open_settings(e):
            current_lang = data_manager.get_settings().get("language", "en")        
            current_provider = data_manager.get_settings().get("ai_provider", "gemini")
            
            # Load all keys to manage state independently
            settings = data_manager.get_settings()
            key_state = {
                "gemini": settings.get("gemini_api_key", ""),
                "openai": settings.get("openai_api_key", ""),
                "openrouter": settings.get("openrouter_api_key", "")
            }

            lang_dropdown = ft.Dropdown(
                label=_t("language"),
                value=current_lang,
                options=[
                    ft.dropdown.Option("en", "English"),
                    ft.dropdown.Option("de", "Deutsch"),
                    ft.dropdown.Option("ja", "日本語"),
                    ft.dropdown.Option("zh", "中文"),
                ],
                border_radius=30,
                border_color=Colors.LAVENDER
            )
            
            provider_dropdown = ft.Dropdown(
                label="AI Provider",
                value=current_provider,
                options=[
                    ft.dropdown.Option("gemini", "Google Gemini"),
                    ft.dropdown.Option("openai", "OpenAI"),
                    ft.dropdown.Option("openrouter", "OpenRouter (DeepSeek Free)"),
                ],
                border_radius=30,
                border_color=Colors.LAVENDER,
                text_size=12
            )

            api_key_input = ft.TextField(
                label="API Key", 
                password=True, 
                can_reveal_password=True,
                value=key_state.get(current_provider, ""),
                border_radius=30,
                border_color=Colors.LAVENDER,
                expand=True
            )

            verify_status = ft.Text("", size=12)

            def on_key_change(e):
                # Update temporary state as user types
                key_state[provider_dropdown.value] = api_key_input.value

            api_key_input.on_change = on_key_change

            def on_provider_change(e):
                val = provider_dropdown.value
                
                # Update Label & Helper
                if val == "openrouter":
                    api_key_input.label = "API Key"
                    api_key_input.hint_text = "Standard Key (Built-in)"
                else:
                    api_key_input.label = "API Key"
                    api_key_input.hint_text = ""
                
                # Swap displayed key
                if val in key_state:
                    api_key_input.value = key_state[val]
                else:
                    api_key_input.value = ""

                # Check if using Default
                if val == "openrouter" and not api_key_input.value:
                    api_key_input.helper_text = "Using built-in Standard Key ✅"
                    api_key_input.helper_style = ft.TextStyle(color=ft.Colors.GREEN)
                else:
                    api_key_input.helper_text = ""

                if api_key_input.page:
                    api_key_input.update()
                
                # Clear status
                verify_status.value = ""
                if verify_status.page:
                    verify_status.update()

            provider_dropdown.on_change = on_provider_change
            
            # Init label
            on_provider_change(None)

            def get_key_url(e):
                if provider_dropdown.value == "gemini":
                    page.launch_url("https://aistudio.google.com/app/apikey")
                elif provider_dropdown.value == "openai":
                    page.launch_url("https://platform.openai.com/api-keys")
                elif provider_dropdown.value == "openrouter":
                    page.launch_url("https://openrouter.ai/keys")

            def verify_key(e):
                verify_status.value = "Verifying..."
                verify_status.color = ft.Colors.ORANGE
                verify_status.update()
                
                temp_key = api_key_input.value
                ai_assistant.set_api_key(temp_key, provider=provider_dropdown.value)
                
                success, msg = ai_assistant.verify_api_key()
                if success:
                    verify_status.value = msg
                    verify_status.color = ft.Colors.GREEN
                else:
                    verify_status.value = msg
                    verify_status.color = ft.Colors.RED
                verify_status.update()

            def clear_key(e):
                api_key_input.value = ""
                key_state[provider_dropdown.value] = ""
                api_key_input.update()
                
                msg = "Regenerated Standard Key (Save to apply)" if provider_dropdown.value == "openrouter" else "Key cleared."
                verify_status.value = msg
                verify_status.color = ft.Colors.GREY
                verify_status.update()

            def save_settings(e):
                # Save ALL keys
                data_manager.update_setting("language", lang_dropdown.value)
                data_manager.update_setting("ai_provider", provider_dropdown.value)
                
                data_manager.update_setting("gemini_api_key", key_state["gemini"])
                data_manager.update_setting("openai_api_key", key_state["openai"])
                data_manager.update_setting("openrouter_api_key", key_state["openrouter"])
                
                # Apply active settings
                active_provider = provider_dropdown.value
                active_key = key_state.get(active_provider, "")
                
                ai_assistant.set_api_key(active_key, provider=active_provider)
                lang_manager.set_language(lang_dropdown.value)
                
                page.close(dialog)
                
                # UI Refresh
                page.title = _t("app_title")
                is_light = page.theme_mode == ft.ThemeMode.LIGHT
                title_text.color = ft.Colors.BLACK if is_light else ft.Colors.WHITE
                title_text.value = _t("app_title")
                
                if page.theme_mode == ft.ThemeMode.LIGHT:
                    theme_icon.tooltip = _t("dark_mode")
                else:
                    theme_icon.tooltip = _t("light_mode")

                todo_view.refresh_view()
                page.update()

            dialog = ft.AlertDialog(
                title=ft.Text(_t("settings_title")),
                content=ft.Column([
                    lang_dropdown,
                    ft.Divider(),
                    ft.Text("AI Configuration", size=14, weight=ft.FontWeight.BOLD),
                    provider_dropdown,
                    ft.Row([
                        api_key_input,
                        ft.IconButton(ft.Icons.KEY, tooltip="Get Key", on_click=get_key_url, icon_color=Colors.LAVENDER),
                        ft.IconButton(ft.Icons.DELETE_OUTLINE, tooltip="Clear/Reset Key", on_click=clear_key, icon_color=ft.Colors.RED_400)
                    ]),
                    ft.ElevatedButton("Verify Connection", on_click=verify_key, bgcolor=Colors.LAVENDER_LIGHT, color=Colors.LAVENDER, height=30),
                    verify_status,
                ], tight=True, spacing=15),
                actions=[
                    ft.TextButton(_t("save"), on_click=save_settings),
                    ft.TextButton(_t("cancel"), on_click=lambda e: page.close(dialog)),
                ],
            )
            page.open(dialog)

        
        # --- UI Layout ---
        theme_icon = ft.IconButton(
            icon=ft.Icons.DARK_MODE if page.theme_mode == ft.ThemeMode.LIGHT else ft.Icons.LIGHT_MODE,
            tooltip=_t("dark_mode") if page.theme_mode == ft.ThemeMode.LIGHT else _t("light_mode"),
            icon_color=Colors.LAVENDER,
            on_click=toggle_theme_mode
        )
        
        mode_icon = ft.IconButton(
            icon=ft.Icons.SHOPPING_CART, # Default
            tooltip=_t("mode_shopping"),
            icon_color=Colors.LAVENDER,
            on_click=toggle_mode
        )
        # Initialize correct state
        update_mode_icon(settings.get("mode", "todo"))
        
        def share_list(e):
            mode = data_manager.get_settings().get("mode", "todo")
            text = data_manager.get_list_as_text(mode)
            encoded_text = urllib.parse.quote(text)
            
            # Try to launch WhatsApp
            whatsapp_url = f"whatsapp://send?text={encoded_text}"
            try:
                page.launch_url(whatsapp_url)
            except Exception as ex:
                print(f"Error launching URL: {ex}")
                # Fallback: Copy to Clipboard
                page.set_clipboard(text)
                page.open(ft.SnackBar(content=ft.Text(_t("copied_to_clipboard"))))

        # --- AI Integration ---
        try:
            from utils.ai_assistant import AIAssistant
            from utils.voice import VOICE_AVAILABLE
        except Exception as e_import:
            raise e_import
        
        # Initialize Assistant
        
        # Load correct key based on saved provider
        saved_provider = settings.get("ai_provider", "gemini")
        if saved_provider == "openrouter":
            api_key = settings.get("openrouter_api_key", "")
        elif saved_provider == "openai":
            api_key = settings.get("openai_api_key", "")
        else:
            api_key = settings.get("gemini_api_key", "")
        
        ai_assistant = AIAssistant(data_manager, api_key)
        
        def open_ai_chat(e):
            # If API key is missing, show "Connect" dialog instead of Chat
            # EXCEPTION: OpenRouter can use the built-in standard key (empty api_key is allowed)
            if not ai_assistant.api_key and ai_assistant.provider != "openrouter":
                def open_settings_for_ai(e):
                    page.close(connect_dialog)
                    open_settings(None)

                connect_dialog = ft.AlertDialog(
                    title=ft.Text("Connect AI 🤖", weight=ft.FontWeight.BOLD),
                    content=ft.Column([
                        ft.Text("To use the AI Assistant, you need to connect your account."),
                        ft.Text(f"Current Provider: {ai_assistant.provider}", size=12, color=ft.Colors.GREY),
                    ], tight=True, spacing=10),
                    actions=[
                        ft.ElevatedButton("Connect", icon=ft.Icons.SETTINGS, on_click=open_settings_for_ai, bgcolor=Colors.LAVENDER, color=ft.Colors.WHITE),
                        ft.TextButton("Cancel", on_click=lambda e: page.close(connect_dialog))
                    ],
                    actions_alignment=ft.MainAxisAlignment.END,
                )
                page.open(connect_dialog)
                return

            # ... Existing Chat Logic ...
            chat_history = ft.ListView(expand=True, spacing=10, auto_scroll=True)
            
            # Define controls first to handle references
            message_input = ft.TextField(hint_text="Ask Listy AI... (e.g. 'Add milk')", expand=True, border_radius=30, border_color=Colors.LAVENDER, focused_border_color=Colors.LAVENDER_LIGHT)
            mic_button = ft.IconButton(icon=ft.Icons.MIC, icon_color=Colors.LAVENDER, tooltip="Speak")
            
            # Conditionally add/remove mic button if Voice is available
            # We will use this below in UI construction

            def send_message(e):
                text = message_input.value
                if not text:
                    return
                
                # Determine Text Color based on Theme
                # User requested Black text ALWAYS for Chat
                chat_text_color = ft.Colors.BLACK 
                
                # User Message
                chat_history.controls.append(
                    ft.Row([
                        ft.Container(
                            content=ft.Text(text, color=chat_text_color, selectable=True),
                            padding=10,
                            border_radius=30,
                            bgcolor=Colors.LAVENDER_LIGHT,
                            width=260, # Constrain width to prevent overflow
                        )
                    ], alignment=ft.MainAxisAlignment.END)
                )
                message_input.value = ""
                
                # Loading Indicator (Spinning)
                loading_view = ft.Row([
                    ft.ProgressRing(width=20, height=20, stroke_width=2, color=Colors.LAVENDER),
                    ft.Text(" Thinking...", italic=True, size=12, color=ft.Colors.GREY)
                ], alignment=ft.MainAxisAlignment.START)
                
                chat_history.controls.append(loading_view)
                page.update()
                
                # AI Response (Background)
                def process_response():
                    try:
                        # Build Context
                        settings = data_manager.get_settings()
                        mode = settings.get("mode", "todo")

                        if mode == "shopping":
                            current_list_id = data_manager.get_current_shopping_list_id()
                            lists = data_manager.get_shopping_lists()
                        else:
                            current_list_id = data_manager.get_current_todo_list_id()
                            lists = data_manager.get_todo_lists()
                            
                        current_list_name = lists.get(current_list_id, "Unknown List")
                        if current_list_id == "default":
                            current_list_name = _t("default_list_name")
                        
                        context_info = f"SYSTEM CONTEXT:\n"
                        context_info += f"- Current App Mode: {mode.upper()}\n"
                        context_info += f"- Active List Name: '{current_list_name}'\n"
                        context_info += f"- Active List ID: '{current_list_id}'\n"
                        context_info += "INSTRUCTION: You MUST add items to this Active List unless the user explicitly names another list. "
                        context_info += f"If the user says 'add x', implies adding to {mode} list '{current_list_name}'."

                        print(f"Sending with context: {context_info}") # Debug
                        
                        response = ai_assistant.send_message(text, context=context_info)
                        
                        # REMOVE LOADING
                        if loading_view in chat_history.controls:
                            chat_history.controls.remove(loading_view)

                        # Update AI Bubble Colors
                        ai_text_color = ft.Colors.BLACK
                        ai_bg_color = ft.Colors.GREY_300 
                        
                        chat_history.controls.append(
                            ft.Row([
                                ft.Container(
                                    content=ft.Text(
                                        response, 
                                        selectable=True, 
                                        color=ai_text_color,
                                        size=14,
                                    ), 
                                    padding=10,
                                    border_radius=30,
                                    bgcolor=ai_bg_color,
                                    width=260, # Constrain width
                                )
                            ], alignment=ft.MainAxisAlignment.START)
                        )
                    except Exception as ex:
                        print(f"Chat Error: {ex}")
                        # REMOVE LOADING ON ERROR
                        if loading_view in chat_history.controls:
                            chat_history.controls.remove(loading_view)
                            
                        chat_history.controls.append(
                            ft.Row([
                                ft.Container(
                                    content=ft.Text(f"Error: {str(ex)}", color=ft.Colors.RED),
                                    padding=10,
                                    border_radius=30,
                                    bgcolor=ft.Colors.GREY_200,
                                )
                            ], alignment=ft.MainAxisAlignment.START)
                        )
                    finally:
                        # Refresh views as lists might have changed
                        todo_view.refresh_view()
                        if todo_view.page:
                            todo_view.update()
                        if chat_history.page:
                            chat_history.update()
                        page.update()
                    
                threading.Thread(target=process_response, daemon=True).start()

            def start_recording(e):
                """Handles voice recording."""
                mic_button.icon_color = ft.Colors.RED
                message_input.hint_text = "Listening..."
                message_input.update()
                mic_button.update()

                def record_thread():
                    try:
                        from utils.voice import VoiceHandler
                        vh = VoiceHandler()
                        if not vh.recognizer:
                             raise Exception("Voice not available")
                        text = vh.listen()
                        if text:
                            message_input.value = text
                            # Auto-send
                            send_message(None)
                    except Exception as ex:
                        page.open(ft.SnackBar(content=ft.Text(f"Error: {str(ex)}"), bgcolor=ft.Colors.RED))
                    finally:
                        mic_button.icon_color = Colors.LAVENDER
                        message_input.hint_text = "Ask Listy AI..."
                        page.update()
                
                threading.Thread(target=record_thread, daemon=True).start()

            # Bind events
            message_input.on_submit = send_message
            mic_button.on_click = start_recording

            # Conditionally build input row
            input_controls = [message_input]
            if VOICE_AVAILABLE:
                input_controls.append(mic_button)
            
            input_controls.append(ft.IconButton(ft.Icons.SEND, icon_color=Colors.LAVENDER, on_click=send_message))

            chat_dialog = ft.AlertDialog(
                title=ft.Row([ft.Text("Listy AI ✨"), ft.IconButton(ft.Icons.CLOSE, on_click=lambda e: page.close(chat_dialog))], alignment=ft.MainAxisAlignment.SPACE_BETWEEN),
                content=ft.Container(
                    content=ft.Column([
                        chat_history,
                        ft.Row(input_controls)
                    ]),
                    width=350,
                    height=500,
                ),
            )
            page.open(chat_dialog)

        ai_icon = ft.IconButton(
            icon=ft.Icons.AUTO_AWESOME,
            icon_color=Colors.LAVENDER,
            tooltip="AI Assistant",
            on_click=open_ai_chat
        )

        menu_bar = ft.Container(
            content=ft.Row(
                controls=[
                    title_text,
                    ft.Row(
                        controls=[
                            ft.IconButton(
                                icon=ft.Icons.SHARE,
                                icon_color=Colors.LAVENDER,
                                tooltip="Share List (WhatsApp)",
                                on_click=share_list
                            ),
                            ai_icon, # New AI Button
                            mode_icon,
                            theme_icon,
                            ft.IconButton(
                                icon=ft.Icons.SETTINGS, 
                                icon_color=Colors.LAVENDER, 
                                tooltip=_t("settings"),
                                on_click=open_settings
                            ),
                        ]
                    )
                ],
                alignment=ft.MainAxisAlignment.SPACE_BETWEEN
            ),
            padding=ft.padding.symmetric(horizontal=15, vertical=10),
        )

        # Clock thread removed as it is no longer used in the UI

        def confirm_clear(e):
            def close_dialog(e):
                page.close(clear_dialog)

            def perform_clear(e):
                mode = data_manager.get_settings().get("mode", "todo")
                data_manager.clear_tasks(mode=mode)
                todo_view.refresh_view()
                page.close(clear_dialog)

            clear_dialog = ft.AlertDialog(
                title=ft.Text(_t("confirm_clear_title")),
                content=ft.Text(_t("confirm_clear_msg")),
                actions=[
                    ft.TextButton(_t("delete_tooltip"), on_click=perform_clear, style=ft.ButtonStyle(color=ft.Colors.RED)),
                    ft.TextButton(_t("cancel"), on_click=close_dialog),
                ],
                actions_alignment=ft.MainAxisAlignment.END,
            )
            page.open(clear_dialog)

        def empty_cart_action(e):
            # Clears only completed items in shopping list
            data_manager.clear_completed_tasks(mode="shopping")
            todo_view.refresh_view()
            page.open(ft.SnackBar(content=ft.Text("Warenkorb geleert!"), bgcolor=Colors.LAVENDER))

        def clear_completed_action(e):
            # Clears only completed items in todo list
            data_manager.clear_completed_tasks(mode="todo")
            todo_view.refresh_view()
            page.open(ft.SnackBar(content=ft.Text("Erledigte Aufgaben gelöscht!"), bgcolor=Colors.LAVENDER))

        # Footer Row
        footer_row = ft.Row(
            controls=[
                ft.TextButton(
                    text=_t("clear_list"),
                    icon=ft.Icons.DELETE_SWEEP,
                    style=ft.ButtonStyle(color=ft.Colors.GREY_500),
                    on_click=confirm_clear
                ),
                ft.Container() # Placeholder, content set by update_footer
            ],
            alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
            vertical_alignment=ft.CrossAxisAlignment.CENTER,
        )

        footer = ft.Container(
            content=footer_row,
            padding=ft.padding.symmetric(horizontal=15, vertical=5),
            bgcolor=ft.Colors.with_opacity(0.05, ft.Colors.BLACK) if page.theme_mode == ft.ThemeMode.LIGHT else ft.Colors.with_opacity(0.2, ft.Colors.BLACK), # Subtle background
            border=ft.border.only(top=ft.border.BorderSide(1, ft.Colors.with_opacity(0.1, Colors.LAVENDER)))
        )

        def update_footer(mode):
            if mode == "shopping":
                # Right side: Empty Cart Button
                footer_row.controls[1] = ft.TextButton(
                    text="Warenkorb leeren",
                    icon=ft.Icons.REMOVE_SHOPPING_CART,
                    style=ft.ButtonStyle(color=ft.Colors.RED_400),
                    on_click=empty_cart_action
                )
            else:
                # Right side: Clear Completed Button (replacing clock)
                footer_row.controls[1] = ft.TextButton(
                    text="Erledigt löschen",
                    icon=ft.Icons.DELETE_OUTLINE,
                    style=ft.ButtonStyle(color=ft.Colors.RED_400),
                    on_click=clear_completed_action
                )
            
            if footer_row.page:
                footer_row.update()

        # Initial footer update
        update_footer(settings.get("mode", "todo"))

        main_layout = ft.Column(
            controls=[
                menu_bar,
                ft.Divider(height=1, color=Colors.LAVENDER_LIGHT),
                todo_view,
                footer
            ],
            expand=True,
            spacing=0
        )

        page.add(main_layout)

    except Exception as e:
        import traceback
        error_trace = traceback.format_exc()
        page.add(
            ft.Column([
                ft.Text("🔥 Critical Error 🔥", color=ft.Colors.RED, size=30, weight=ft.FontWeight.BOLD),
                ft.Text(f"Error: {str(e)}", color=ft.Colors.RED),
                ft.Container(
                    content=ft.Text(error_trace, size=10, font_family="monospace"),
                    bgcolor=ft.Colors.GREY_900 if page.theme_mode == ft.ThemeMode.DARK else ft.Colors.GREY_200,
                    padding=10,
                    expand=True
                )
            ], scroll=ft.ScrollMode.ALWAYS, expand=True)
        )


if __name__ == "__main__":
    ft.app(target=main)