SUGGESTIONS = [
    # A
    "Aal", "Aalsuppe", "Abdeckband", "Abdeckfolie", "Abflussreiniger", "Abschminkpads", "Aceto Balsamico", "Achselpads", "Adapter", "Agavendicksaft", "Ahornsirup", "Ajvar", "Akkus", "Akkuschrauber", "Aktenordner", "Alkoholfreies Bier", "Allzweckreiniger", "Alufolie", "Amarettini", "Amaretto", "Ananas", "Ananassaft", "Anchovis", "Andalusische Soße", "Angostura", "Anis", "Antipasti", "Apfel", "Äpfel", "Apfelkuchen", "Apfelmus", "Apfelsaft", "Apfelschorle", "Apfelstrudel", "Apfelwein", "Aprikosen", "Aprikosenkonfitüre", "Aprikosennektar", "Arbeitshandschuhe", "Artischocken", "Artischockenherzen", "Asiasauce", "Atemerfrischer", "Aubergine", "Aufbackbrötchen", "Aufschnitt", "Aufschnittwurst", "Augentropfen", "Austern", "Austernpilze", "Austernsauce", "Auto-Duftbaum", "Autolack", "Autoshampoo", "Autoschwamm", "Avocado", "Avocadoöl", "Ayran",

    # B
    "Babybrei", "Babybadelotion", "Babycreme", "Babymilch", "Babyöl", "Babypuder", "Babyshampoo", "Babyspinat", "Babytücher", "Backaroma", "Backcamembert", "Backerbsen", "Backfisch", "Backkakao", "Backmischung", "Backpapier", "Backpflaumen", "Backpulver", "Backtrennspray", "Bacon", "Badreiniger", "Badesalz", "Badeschwamm", "Baguette", "Baguettebrötchen", "Baileys", "Balsamico", "Balsamico Creme", "Bambussprossen", "Bananen", "Bananenchips", "Bananensaft", "Bandnudeln", "Barbecuesauce", "Bärenmarke", "Bärlauch", "Bärlauchpesto", "Basilikum", "Basmati Reis", "Batterien", "Bauernbrot", "Bauernfrühstück", "Baumkuchen", "Becher", "Béchamelsoße", "Beerenmischung (TK)", "Beef Jerky", "Beinscheibe", "Benzin", "Bergkäse", "Bernstein Makrele", "Besen", "Bier", "Bierwurst", "Binden", "Bio-Müllbeutel", "Birnen", "Birnensaft", "Biskuitboden", "Biskuitrolle", "Bit-Set", "Bitter Lemon", "Bitterschokolade", "Blätterteig", "Blattgelatine", "Blattspinat", "Blaubeeren", "Blauschimmelkäse", "Bleichmittel", "Bleistifte", "Blockbatterie", "Blumen", "Blumenerde", "Blumenkohl", "Blumentopf", "Blutdruckmessgerät", "Blutorangen", "Bockwurst", "Bohnen (Dose)", "Bohnen (grün)", "Bohneneintopf", "Bohnenkraut", "Bohrer", "Bohrmaschine", "Bolognese Sauce", "Bonbons", "Bohnensalat", "Bratenthermometer", "Brathering", "Bratkartoffeln", "Bratwurst", "Brausepulver", "Brechbohnen", "Bremsflüssigkeit", "Bresaola", "Briefumschläge", "Brezen", "Brie", "Briefmarken", "Brioche", "Brokkoli", "Brombeeren", "Brombeermarmelade", "Brot", "Brotchips", "Brötchen", "Brottrunk", "Brownies", "Brühe", "Brühwürfel", "Brustfilet", "Buchstaben-Nudeln", "Buchweizen", "Büffelmozzarella", "Bügelbrettbezug", "Bügelwasser", "Bulgur", "Buntstifte", "Burgersauce", "Bunten Streusel", "Burrata", "Büroklammern", "Butter", "Buttergemüse", "Butterkeks", "Buttermilch", "Butaris", "Butterschmalz",

    # C
    "Cabbanossi", "Caesar Dressing", "Calamari", "Camembert", "Campari", "Cannelloni", "Cantaloupe Melone", "Cappucchino", "Caramelsirup", "Carbonara Sauce", "Carpaccio", "Cashewkerne", "Cashewmus", "Cassler", "Cayennepfeffer", "CD-Rohlinge", "Cevapcici", "Champagner", "Champignons", "Champignons (Dose)", "Cheddar", "Chia-Samen", "Chicken Nuggets", "Chicken Wings", "Chicoree", "Chili Vergetarisch", "Chili con Carne", "Chili Cheese Nuggets", "Chilis", "Chilisauce", "Chinagohl", "Chinapfanne", "Chips", "Chorizo", "Christstollen", "Chutney", "Ciabatta", "Cider", "Clementinen", "Cocktailkirschen", "Cocktailsoße", "Cocktailtomaten", "Cognac", "Cola", "Cola Zero", "Computerzeitschrift", "Conditioner", "Cookie Dough", "Cookies", "Cornflakes", "Corned Beef", "Cornichons", "Couscous", "Cracker", "Cranberries", "Creme double", "Creme fin", "Creme Fraiche", "Crepes", "Croissants", "Croutons", "Curry Wurst", "Curryketchup", "Currypaste", "Currypulver",

    # D
    "Damenbinden", "Datteln", "Dauerwurst", "Deckweiß", "Deko", "Deo", "Deoroller", "Desinfektionsmittel", "Dessertsoße", "Deutsche Markenbutter", "Diätmargarine", "Dichtungsring", "Dickmilch", "Dill", "Dinkelbrot", "Dinkelmehl", "Dinkelwaffeln", "Dip", "Disketten", "Döner", "Donuts", "Doppelkeks", "Dorade", "Dosenananas", "Dosenerbsen", "Dosenfrüchte", "Dosenmandarinen", "Dosenmais", "Dosenmilch", "Dosenpfirsiche", "Dosenpilze", "Dosenravioli", "Dosensuppen", "Dosentomaten", "Drachenfrucht", "Draht", "Drahtbürste", "Dressing", "Drops", "Druckerpapier", "Druckerpatronen", "Dübel", "Duftstein", "Dunkles Bier", "Dünger", "Duschdas", "Duschgel", "DVD-Rohlinge",

    # E
    "Earl Grey Tee", "Edamame", "Edamer", "Edelbitterschokolade", "Eichelschwein", "Eier", "Eier (Bio)", "Eierlikör", "Eiernudeln", "Eiersalat", "Eimer", "Einwegbecher", "Einweghandschuhe", "Einwegrasierer", "Einweggeschirr", "Eintopf", "Eis", "Eis am Stiel", "Eisbergsalat", "Eisen-Tabletten", "Eiskaffee", "Eiskonfekt", "Eiskratzer", "Eiscreme", "Eistee", "Eiswaffeln", "Eiswürfel", "Emmentaler", "Energy Drink", "Ente", "Enteiser", "Enteiserspray", "Entenbrust", "Entkalker", "Erbsen", "Erbsen & Wurzeln", "Erbseneintopf", "Erdbeeren", "Erdbeereis", "Erdbeerkonfitüre", "Erdbeermilch", "Erdnüsse", "Erdnussbutter", "Erdnussflips", "Erdnussöl", "Ersatzlampen", "Ersatzmilch", "Erste-Hilfe-Set", "Essig", "Essigessenz", "Essiggurken", "Espresso", "Espressobohnen", "Estragon", "Etikettenlöser", "Exquisa",

    # F
    "Fajita", "Falafel", "Fanta", "Farfalle", "Farb- und Schmutzfangtücher", "Färbemittel", "Farbe", "Farbrolle", "Fahrradöl", "Fahrradschloss", "Fassbrause", "Federweißer", "Feigen", "Feigen Senf", "Feinrippunterwäsche", "Feuchttücher", "Fenchel", "Fencheltee", "Fensterreiniger", "Fertiggericht", "Fertigteig", "Feta", "Fettuccine", "Feuerzeug", "Feuerzeuggas", "Filetstreifen", "Filzstifte", "Fineliner", "Fisch", "Fisch (TK)", "Fischstäbchen", "Fleckensalz", "Fleisch", "Fleischextrakt", "Fleischkäse", "Fleischsalat", "Fleischwurst", "Fliederbeersaft", "Fliesenkleber", "Flüssigseife", "Flusskrebse", "Folienkartoffel", "Fondant", "Fondor", "Fonduefleisch", "Fonduekäse", "Forelle", "Formfleisch", "Franzbrötchen", "Frikadellen", "Frischhaltefolie", "Frischkäse", "Frittierfett", "Fruchteis", "Früchtemüsli", "Früchtetee", "Fruchtgummi", "Fruchtjoghurt", "Fruchtsaft", "Fruchtzwerge", "Frühlingsrollen", "Frühlingssuppe", "Frühlingszwiebeln", "Früchtequark", "Fugendichter", "Füller", "Füllfederhalter", "Fusilli", "Fußball", "Fußcreme",

    # G
    "Gabelspaghetti", "Galgant", "Gans", "Gänsebraten", "Gänsebrust", "Garn", "Garnelen", "Gartenschere", "Gartenkräuter", "Gebäck", "Geburtstagskerzen", "Geflügel", "Geflügelfond", "Geflügelsalat", "Geflügelwurst", "Gefrierbeutel", "Gelatine", "Gelbwurst", "Gelee", "Gemüse", "Gemüse (TK)", "Gemüsebrühe", "Gemüsesaft", "Gemüsestäbchen", "Gemüsepfanne", "Geräucherter Fisch", "Geräucherter Lachs", "Geräucherter Schinken", "Gerste", "Geschenkbox", "Geschenkpapier", "Geschirrspülmittel", "Geschirrspülsalz", "Geschirrtabs", "Getrocknete Tomaten", "Gewürzgurken", "Gewürzketchup", "Gewürznelken", "Gewürzspekulatius", "Gewürze", "Gießkanne", "Gips", "Gin", "Gin Tonic", "Ginger Ale", "Girlanden", "Glasnudeln", "Glasreiniger", "Glühbirnen", "Glühwein", "Glutenfreies Brot", "Gnocchi", "Gorgonzola", "Gouda", "Granatapfel", "Grapefruit", "Grapefruitsaft", "Gratinkäse", "Graubrot", "Graupen", "Griechischer Joghurt", "Grieß", "Grießbrei", "Grießnockerl", "Grillanzünder", "Grillbriketts", "Grittibänz", "Grillfackeln", "Grillfleisch", "Grillgemüse", "Grillgewürz", "Grillkäse", "Grillkohle", "Grillreiniger", "Grillsoße", "Grillwurst", "Grundierung", "Grüne Bohnen", "Grüne Soße", "Grünkern", "Grünkohl", "Guacamole", "Gulasch", "Gulaschsuppe", "Gulden Draak", "Gummibärchen", "Gummihandschuhe", "Gurke", "Gurkensalat", "Gyros",

    # H
    "Haargel", "Haargummi", "Haarklammern", "Haarkur", "Haaröl", "Haarspray", "Haarspülung", "Hackbällchen", "Hackbraten", "Hackfleisch", "Hackfleisch (halb/halb)", "Hackfleisch (Rind)", "Haferdrink", "Haferflocken", "Haferkekse", "Haferkleie", "Hafermilch", "Hagebuttentee", "Hähnchen", "Hähnchenbrust", "Hähnchenbrustfilet", "Hähnchengeschnetzeltes", "Hähnchenkeulen", "Hähnchenschenkel", "Hähnchenschnitzel", "Haifischflossensuppe", "Halloumi", "Halsbonbons", "Hamburger Brötchen", "Hamburger Fleisch", "Hammer", "Handcreme", "Handfeger", "Handseife", "Handtuchpapier", "Hanföl", "Harrissa", "Hartkäse", "Haselnüsse", "Haselnusscreme", "Haselnussschnaps", "Hausmacher Wurst", "Hautcreme", "Hefe", "Hefeklöße", "Hefeteig", "Heftklammern", "Heftpflaster", "Heidelbeeren", "Heilbutt", "Hering", "Heringsfilet", "Heringssalat", "Herz", "Heumann Tee", "Himbeeren", "Himbeereis", "Himbeergeist", "Himbeerkonfitüre", "Himbeersaft", "Himmeltau", "Hirschbraten", "Hirschgulasch", "Hirse", "Hirtenkäse", "Hobel", "Hoisin Sauce", "Hollandaise", "Holundersaft", "Holz", "Holzleim", "Holzschutzlasur", "Holzspieße", "Honig", "Honigmelone", "Honigsenf", "Hops", "H-Milch", "H-Sahne", "Hummer", "Hummus", "Hundefutter", "Hundeleckerli", "Hüstel", "Hustenbonbons", "Hustensaft", "Hüttenkäse", "Hygieneartikel", "Hühnerbrühe", "Hühnerfrikassee", "Hühnerherzen", "Hühnerklein", "Hühnerleber", "Hühnernudeltopf", "Hühnersuppe",

    # I
    "Ibuprofen", "Ingwer", "Ingwerbier", "Ingwerpulver", "Ingwershot", "Ingwertee", "Insektenspray", "Instantkaffee", "Instantnudeln", "Instantsuppe", "Isodrink", "Isolierband",

    # J
    "Jägermeister", "Jagdwurst", "Jakobsmuscheln", "Jalapenos", "Javazucker", "Jever", "Jodsalz", "Joghurt", "Joghurt (Natur)", "Joghurt Drink", "Johannisbeeren", "Johannisbeersaft", "Johannisbrotkernmehl", "Joppiesauce", "Jujube", "Jungbullensteak", "Junket",

    # K
    "Kabelbinder", "Kabeljau", "Kaffee", "Kaffeebohnen", "Kaffeefilter", "Kaffeelikör", "Kaffeepads", "Kaffeepulver", "Kaffeesahne", "Kaffeesirup", "Kaiserdaten", "Kaisergemüse", "Kaiserschmarrn", "Kakao", "Kakaobutter", "Kakaopulver", "Kaki", "Kalbsbraten", "Kalbsfilet", "Kalbsgulasch", "Kalbsleber", "Kalbsleberwurst", "Kalkreiniger", "Kalbsmedaillons", "Kalbsrücken", "Kalbssteak", "Kamillentee", "Kaninchen", "Käppchen", "Kapern", "Karamell", "Karamellbonbons", "Karamellpudding", "Karamellsoße", "Karotten", "Karottensaft", "Karpfen", "Karteikarten", "Kartoffelbrei", "Kartoffelchips", "Kartoffelklöße", "Kartoffelmehl", "Kartoffeln", "Kartoffelpuffer", "Kartoffelsalat", "Kartoffelsuppe", "Käse", "Käseaufschnitt", "Käsebrötchen", "Käsefondue", "Käsekuchen", "Käsespätzle", "Kasseler", "Katzenfutter", "Katzenstreu", "Kaugummi", "Kaviar", "Kefir", "Kehrblech", "Kekse", "Kerbel", "Kernseife", "Kerzen", "Ketchup", "Kichererbsen", "Kichererbsenmehl", "Kinder Kekse", "Kinder Schokolade", "Kinderschokolade", "Kidneybohnen", "Kieler Sprotten", "Kimchi", "Kirschen", "Kirschkonfitüre", "Kirschsaft", "Kirschtomaten", "Kirschwasser", "Kiwi", "Klarspüler", "Klebeband", "Klebstoff", "Kleiderbügel", "Klementinen", "Klöße", "Knäckebrot", "Knete", "Kneifzange", "Knoblauch", "Knoblauchbaguette", "Knoblauchcreme", "Knoblauchgranulat", "Knoblauchpresse", "Knoblauchsoße", "Knödel", "Knopfzellen", "Kochbeutelreis", "Kochbuch", "Kochkäse", "Kochsahne", "Kochschinken", "Kochwurst", "Kohl", "Kohlrabi", "Kohlrouladen", "Kokosflocken", "Kokosmakronen", "Kokosmilch", "Kokosnuss", "Kokosöl", "Kokosraspel", "Kokoswasser", "Kombucha", "Kondensmilch", "Kondome", "Konfekt", "Konfitüre", "Kopfsalat", "Kopfhörer", "Kopfschmerztabletten", "Koriander", "Korn", "Kornflakes", "Körperlotion", "Krabben", "Krabbenbrot", "Kräcker", "Krapfen", "Kräuter", "Kräuter der Provence", "Kräuterbaguette", "Kräuterbonbons", "Kräuterbutter", "Kräuterfrischkäse", "Kräuterlikör", "Kräuterquark", "Kräutersalz", "Kräutertee", "Krawatte", "Kren", "Kresse", "Kreuzkümmel", "Krokant", "Kroketten", "Kronsbeeren", "Krupuk", "Kuchen", "Kuchenglasur", "Küchenrolle", "Kugelschreiber", "Kümmel", "Kumquats", "Kürbis", "Kürbiskernbrot", "Kürbiskerne", "Kürbiskernöl", "Kürbissuppe", "Kurkuma",

    # L
    "Lachs", "Lachiersatz", "Lachsfilet", "Lachsschinken", "Lack", "Ladekabel", "Lakritz", "Lammfilet", "Lammfleisch", "Lammkotelett", "Lammlachse", "Lammrücken", "Lampenöl", "Lasagne", "Lasagneplatten", "Lasur", "Litschis", "Laufschuhe", "Lauch", "Lauchzwiebeln", "Laugenbrötchen", "Laugengebäck", "Laugenstangen", "Lavendel", "Lebkuchen", "Leber", "Leberkäse", "Leberknödel", "Leberwurst", "Lederpflege", "Leim", "Leinöl", "Leinsamen", "Lemon Curd", "Liebstöckel", "Limette", "Limettensaft", "Limonade", "Lineal", "Linsen", "Linseneintopf", "Linsensuppe", "Lippenpflege", "Lippenstift", "Litschi", "Locher", "Löffelbiskuits", "Lollipops", "Lorbeerblätter", "Lötkolben", "Löwenzahntee", "Lufterfrischer", "Luftballons", "Lumpenzucker", "Lutscher", "Lütticher Waffeln",

    # M
    "Maasdammer", "Macadamia", "Macarons", "Machetes", "Magarine", "Maggi", "Magerquark", "Mais", "Maisgrieß", "Maiskolben", "Maismehl", "Maissalat", "Maiswaffeln", "Majoran", "Makrelen", "Malerrolle", "Maltbier", "Malzbier", "Mandarienen", "Mandelmilch", "Mandelmus", "Mandeln", "Mandeln (gehackt)", "Mandeln (gemahlen)", "Mango", "Mangosaft", "Mangold", "Manuka Honig", "Mäppchen", "Margarine", "Marker", "Marillen", "Marillenmarmelade", "Maronen", "Marzipan", "Marzipanbrot", "Mascarpone", "Maßband", "Matschbrötchen", "Matjes", "Matjesfilet", "Maultaschen", "Maulwurfskuchen", "Mayonnaise", "Meersalz", "Meeresfrüchte", "Mehrkornbrötchen", "Mehl", "Melasse", "Melissengeist", "Melone", "Menüschalen", "Mentos", "Merrettich", "Mett", "Mettenden", "Mettwurst", "Miesmuscheln", "Milch", "Milch (1,5%)", "Milch (3,5%)", "Milchbrötchen", "Milchpulver", "Milchreis", "Milchschnitte", "Milchshake", "Mineralwasser", "Mineralwasser (Medium)", "Mineralwasser (Still)", "Minze", "Mirabellen", "Miracoli", "Miso-Paste", "Mohn", "Mohnbrötchen", "Mohnback", "Mohnkuchen", "Mohrenkopf", "Mohrrüben", "Mondamin", "Mörtel", "Mon Cheri", "Mortadella", "Moselwein", "Mostrich", "Motoröl", "Mozzarella", "Müllbeutel", "Müllsäcke", "Multivitaminsaft", "Mundspülung", "Mundwasser", "Mürbeteig", "Muscheln", "Müsli", "Müsliriegel", "Muskatnuss", "Muttern", "Muttertagsgeschenk", "Mutzbraten",

    # N
    "Nachos", "Nachtcreme", "Nähgarn", "Nägel", "Nagellack", "Nagellackentferner", "Nagelzange", "Nahrungsergänzungsmittel", "Nashi Birne", "Nasenspray", "Nassrasierer", "Natron", "Nektarinen", "Nelken", "Nimm2", "Nieren", "Nockerln", "Nonpareilles", "Noriblätter", "Notizblock", "Notizheft", "Nougat", "Nougatcreme", "Nudeln", "Nudelauflauf", "Nabelsalat", "Nudelsalat", "Nudelsoße", "Nudelsuppe", "Nürnberger Würstchen", "Nuss-Nougat-Creme", "Nusskuchen", "Nussmischung", "Nussschokolade", "Nüsse", "Nutella",

    # O
    "Obazda", "Oberkeule (Hähnchen)", "Obst", "Obstboden", "Obstgarten", "Obstkonserven", "Obstler", "Obstsalat", "Ochsenschwanz", "Ochsenzieme", "Ofenkäse", "Ohrenstäbchen", "Okra", "Oliven", "Oliven (grün)", "Oliven (schwarz)", "Olivenbrot", "Olivenöl", "Omelett", "Orangen", "Orangenlimonade", "Orangenmarmelade", "Orangensaft", "Ordner", "Oregano", "Oreo", "Osterhasi", "Osterei", "Ouzo", "Ovomaltine",

    # P
    "Pakk Choi", "Palmin", "Palmöl", "Pampers", "Pancake Mix", "Pancakes", "Paniermehl", "Panna Cotta", "Papaya", "Papier", "Pappbecher", "Pappteller", "Paprika", "Paprika (edelsüß)", "Paprika (gelb)", "Paprika (grün)", "Paprika (rosenscharf)", "Paprika (rot)", "Paprikachips", "Paprikamark", "Paprikapulver", "Parademois", "Paradiescreme", "Paranüsse", "Parfüm", "Parmesan", "Parma Schinken", "Partyhüte", "Pasta", "Pastinaken", "Pastete", "Patros", "Pecanüsse", "Peperoni", "Pepsi", "Perlgraupen", "Pesto", "Pesto Genovese", "Pesto Rosso", "Petersilie", "Petersilienwurzel", "Pez", "Pfannekuchen", "Pfanner Eistee", "Pfeffer", "Pfeffer (schwarz)", "Pfeffer (weiß)", "Pfefferkörner", "Pfefferminze", "Pfefferminztee", "Pfeffermühle", "Pfeiffer", "Pfifferlinge", "Pfirsiche", "Pfirsiche (Dose)", "Pfirsichsaft", "Pflanzencreme", "Pflanzenfett", "Pflanzenöl", "Pflanzentopf", "Pflaster", "Pflaumen", "Pflaumenmus", "Pflaumenwein", "Physalis", "Pick Up", "Piment", "Pinienkerne", "Pinsel", "Pistazien", "Pita Brot", "Pizza", "Pizza (TK)", "Pizza Hawaii", "Pizza Margherita", "Pizza Salami", "Pizzaboden", "Pizzagewürz", "Pizzakäse", "Pizzasoße", "Pizzateig", "Planen", "Plätzchen", "Plastikbecher", "Plastiktüten", "Polenta", "Pomelo", "Pommes Frites", "Pommesgewürz", "Popcorn", "Poree", "Portwein", "Postkarten", "Pralinen", "Preiselbeeren", "Preiselbeermarmelade", "Pressack", "Prinzenrolle", "Prosecco", "Proteinbrot", "Proteinriegel", "Provolone", "Puderzucker", "Pumpernickel", "Punsch", "Pute", "Putenbraten", "Putenbrust", "Putenbrustaufschnitt", "Putengeschnetzeltes", "Putenleber", "Putenschnitzel", "Putencurry", "Putzlappen", "Putzmittel", "Putztuch",

    # Q
    "Quark", "Quarkbällchen", "Quarktasche", "Quetschies", "Quiche", "Quinoa", "Quitten", "Quittengelee",

    # R
    "Raclettekäse", "Radicchio", "Radieschen", "Radler", "Radierschummi", "Rahm", "Rahmgeschnetzeltes", "Rahmsoße", "Rahmspinat", "Rapsöl", "Rasierer", "Rasierklingen", "Rasierschaum", "Ratatouille", "Räucheraal", "Räucherforelle", "Räucherlachs", "Räucherkäse", "Ravioli", "Rebhuhn", "Regenbogenforelle", "Rehbraten", "Rehgulasch", "Rehkeule", "Rehrücken", "Reibekuchen", "Reibekäse", "Reinigungsbenzin", "Reinigungstücher", "Reis", "Reisessig", "Reisflocken", "Reismilch", "Reisnudeln", "Reiswaffeln", "Remoulade", "Rettich", "Rhabarber", "Ricotta", "Riegel", "Riesling", "Rinderbeinscheibe", "Rinderbraten", "Rinderbrühe", "Rinderfilet", "Rinderfonds", "Rindergeschnetzeltes", "Rindergulasch", "Rinderhack", "Rinderhüfte", "Rinderleber", "Rinderrouladen", "Rindersalami", "Rinderschinken", "Rindersteak", "Rindfleisch", "Risottoreis", "Ritter Sport", "Roastbeef", "Roggenbrot", "Roggenmehl", "Rohrzange", "Rohrzucker", "Rollmops", "Romanasalat", "Roquefort", "Rosenkohl", "Rosinen", "Rosmarin", "Rostbratwürstchen", "Rote Beete", "Rote Beete (Glas)", "Rote Grütze", "Rote Linsen", "Rotbarsch", "Rotkohl", "Rotwein", "Rotweinessig", "Röstzwiebeln", "Rouladen", "Rucola", "Rührei", "Rum", "Rumpsteak", "Russisch Brot",

    # S
    "Safran", "Saft", "Sage", "Sago", "Sahne", "Sahnehering", "Sahnejoghurt", "Sahnekeffir", "Sahnesteif", "Salami", "Salamisticks", "Salat", "Salatcreme", "Salatgurke", "Salatkräuter", "Salatmix", "Salatöl", "Salatsoße", "Salbei", "Salz", "Salzstangen", "Sambal Oelek", "Sanddornsaft", "Sandwich", "Sandwichtoast", "Sanella", "Sardellen", "Sardellenpaste", "Sardinen", "Sate-Spieße", "Sauerbraten", "Sauerkirschen", "Sauerkraut", "Sauerkrautsaft", "Sauerrahm", "Sauerteig", "Säge", "Schabefleisch", "Schafskäse", "Schalotten", "Scheibenwischwasser", "Scheuermilch", "Schichtkäse", "Schill", "Schinken", "Schinken (gekocht)", "Schinken (roh)", "Schinkenwürfel", "Schlagsahne", "Schleifpapier", "Schmalz", "Schmand", "Schmelzkäse", "Schmelzflocken", "Schneidebohnen", "Schnittkäse", "Schnittlauch", "Schnitzel", "Schnuller", "Schokolade", "Schokoladeneis", "Schokoladenpudding", "Schokomilch", "Schokomüsli", "Schokoriegel", "Schokosoße", "Schokostreusel", "Scholle", "Schollenfilet", "Schrauben", "Schraubendreher", "Schraubenschlüssel", "Schraubenzieher", "Schuhcreme", "Schuhsolen", "Schuhspray", "Schulhefte", "Schupfnudeln", "Schwamm", "Schwammtücher", "Schwarzwurzeln", "Schweinebauch", "Schweinebraten", "Schweinefilet", "Schweinefleisch", "Schweinegulasch", "Schweinehaxe", "Schweinekamm", "Schweinekotelett", "Schweinelenden", "Schweineleber", "Schweinemedaillons", "Schweinenacken", "Schweinenackensteak", "Schweinrücken", "Schweineschnitzel", "Schwedenhappen", "Schweppes", "Seelachs", "Seeungeheuer", "Seezunge", "Seife", "Seifenblasen", "Seitan", "Sekt", "Sellerie", "Selleriesalz", "Semmelbrösel", "Semmelknödel", "Senf", "Senfgurken", "Senfkörner", "Servietten", "Serviettenknödel", "Sesam", "Sesamöl", "Shampoo", "Sheabutter", "Sherry", "Shrimps", "Sicherheitsnadeln", "Siedesalz", "Siirup", "Silikon", "Sild", "Silberzwiebeln", "Smoothie", "Snickers", "Soda", "Softdrinks", "Soja", "Sojabohnen", "Sojagranulat", "Sojamehl", "Sojamilch", "Sojasoße", "Socken", "Soljanka", "Sonnenblumenkerne", "Sonnenblumenöl", "Sonnencreme", "Sonnenmilch", "Soßenbinder", "Souvlaki", "Spachtel", "Spaghetti", "Spaghettieis", "Spaghetti Bolognese", "Spanferkel", "Spargel", "Spargel (Glas)", "Spargelsuppe", "Spanngurt", "Spätzle", "Speck", "Speckwürfel", "Speiseöl", "Speisequark", "Speisesalz", "Speisestärke", "Spekulatius", "Spiegel", "Spielzeug", "Spiegelei", "Spinat", "Spiritus", "Sportgetränk", "Sprossen", "Sprühfelt", "Sprühsahne", "Spülbürste", "Spülmaschinenreiniger", "Spülmaschinensalz", "Spülmaschinentabs", "Spülmittel", "Spülschwamm", "Stachelbeeren", "Stangensellerie", "Steak", "Steakpfeffer", "Steaksauce", "Steckerleiste", "Steinbeißer", "Steinbutt", "Steinpilze", "Sternanis", "Stichsäge", "Stilfser", "Streichhölzer", "Streichkäse", "Streichwurst", "Studentenfutter", "Sultaninen", "Suppe", "Suppengemüse", "Suppenhuhn", "Suppennudeln", "Sushi", "Sushi Reis", "Süßigkeiten", "Süßkartoffeln", "Süßstoff", "Süßwarter", "Szegediner Gulasch",

    # T
    "Tabasco", "Tabletten", "Tacker", "Tackernadeln", "Tacos", "Tacosschalen", "Tafelspitz", "Tafelwasser", "Tagliatelle", "Tahini", "Tamarinde", "Tandoori Paste", "Tannenbäume", "Tapete", "Tapetenkleister", "Taschen", "Taschenlampen", "Taschentücher", "Tee", "Teebeutel", "Teelichter", "Teewurst", "Teigwaren", "Tempeh", "Tempura", "Teppichmesser", "Teriyaki Sauce", "Tesafilm", "Tetra Pak", "Textmarker", "Thunfisch", "Thunfisch (Dose)", "Thunfischsteak", "Thymian", "Tic Tac", "Tiefkühlobst", "Tiefkühlpizza", "Tierfutter", "Tilsiter", "Tintenfisch", "Tintenfischringe", "Tiramisu", "Toast", "Toastbrot", "Toffifee", "Tofu", "Toilettenpapier", "Toilettenreiniger", "Tomaten", "Tomaten (passiert)", "Tomaten (gestückelt)", "Tomatenmark", "Tomatensaft", "Tomatensoße", "Tomatensuppe", "Tonic Water", "Topfschwamm", "Topinambur", "Tortellini", "Tortenboden", "Tortenguss", "Tortillas", "Tortillachips", "Trauben", "Traubenkernöl", "Traubensaft", "Traubenzucker", "Trockenhefe", "Trockenobst", "Trockenpflaumen", "Trolli", "Trüffel", "Trüffelöl", "Truthahn", "Truthahnbrust", "Tsatsiki", "Tuna", "Twix",

    # U
    "Überraschungsei", "Udon-Nudeln", "Unkrautvernichter", "Unterhose", "Unterlegscheiben", "Unterwäsche", "Urlaub", "Uhu", "USB-Stick",

    # V
    "Vanish", "Vanille", "Vanilleeis", "Vanilleextrakt", "Vanillekipferl", "Vanillemilch", "Vanillepaste", "Vanillepudding", "Vanilleschote", "Vanillasoße", "Vanillezucker", "Vaseline", "Veganer Aufschnitt", "Veganer Käse", "Veganer Joghurt", "Vegetarische Bratwurst", "Vegetarische Wurst", "Veltins", "Verband", "Verlängerungskabel", "Vio", "Vitamin C", "Vitamine", "Vogelfutter", "Volvic", "Vollkornbrot", "Vollkornmehl", "Vollkornnudeln", "Vollkornreis", "Vollmilch", "Vollmilchschokolade", "Vongole", "Vorderhaxe",

    # W
    "Wacholderbeeren", "Wachs", "Waffeln", "Waffeleisen", "Waffelröllchen", "Walnüsse", "Walnusskernöl", "Walnussöl", "Wandfarbe", "Wasabi", "Waschbenzin", "Wäscheklammern", "Waschmittel", "Wäschespinne", "Wäscheständer", "Wasser", "Wassereis", "Wasserkastanien", "Wassermelone", "Wasserwaage", "Watte", "Wattebausch", "Wattepads", "Wattestäbchen", "WC-Ente", "WC-Papier", "WC-Reiniger", "WC-Stein", "Weichkäse", "Weichspüler", "Weihnachtsmann", "Weihnachtsstollen", "Wein", "Weinblätter", "Weindrink", "Weine", "Weinessig", "Weingummi", "Weinsteinbackpulver", "Weintrauben", "Weußbrot", "Weißkohl", "Weißwein", "Weißweinessig", "Weißwurst", "Weizenbier", "Weizenkeimöl", "Weizenkleie", "Weizenmehl", "Weizentortillas", "Wellfleisch", "Werkzeug", "Werkzeugkoffer", "Werthers Echte", "Whiskey", "Wiener", "Wiener Boden", "Wiener Schnitzel", "Wiener Würstchen", "Wild", "Wildlachs", "Wildreis", "Wildschwein", "Windbeutel", "Windeln", "Winkel", "Wirsing", "Wischlappen", "Wodka", "Wolfsbarsch", "Worcester Sauce", "Wunderkerzen", "Wundsalbe", "Wurst", "Wurstaufschnitt", "Wurzelspeck", "Wurzel",

    # X
    "Xylit",

    # Y
    "Yakult", "Yams", "Yoghurt", "Yop", "Ysop",

    # Z
    "Zahnbürste", "Zahncreme", "Zahnpasta", "Zahnseide", "Zahnstocher", "Zander", "Zanderfilet", "Zange", "Zaziki", "Zeitschriften", "Zewa", "Ziegenfrischkäse", "Ziegenkäse", "Zigaretten", "Zigarillos", "Zimt", "Zimsterne", "Zinksalbe", "Zitrone", "Zitroneneis", "Zitronengras", "Zitronenmelisse", "Zitronenpfeffer", "Zitronensäure", "Zitronensaft", "Zitronenschale", "Zitronentee", "Zollstock", "Zucchini", "Zucker", "Zuckererbsen", "Zuckerrübensirup", "Zuckerwatte", "Zungenwurst", "Zwetschgen", "Zwieback", "Zwiebeln", "Zwiebeln (rot)", "Zwiebelsuppe", "Zwiebelwurst"
]
